export const CLEAR_SYSTEM_ALERT = 'CLEAR_SYSTEM_ALERT';
export const WILL_CLEAR_SYSTEM_ALERT = 'WILL_CLEAR_SYSTEM_ALERT';
export const CLEAR_ALL_SYSTEM_ALERTS = 'CLEAR_ALL_SYSTEM_ALERTS';
export const API_FAILURE = 'API_FAILURE';
export const ADD_ALERT = 'ADD_ALERT';